# Generated by Django 5.0.3 on 2024-09-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'Robots', 'verbose_name_plural': 'Robots'},
        ),
    ]
