# Generated by Django 5.0.3 on 2024-09-21 09:13

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_robots_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOStaticPage',
            fields=[
                ('page', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='страница')),
            ],
            options={
                'verbose_name': 'SEO для статических страниц',
                'verbose_name_plural': 'SEO для статических страниц',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SEOStaticPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('header', models.CharField(max_length=255, unique=True, verbose_name='h1')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('noindex_follow', models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='seo.seostaticpage')),
            ],
            options={
                'verbose_name': 'SEO для статических страниц Translation',
                'db_table': 'seo_seostaticpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
