# Generated by Django 5.0.3 on 2024-09-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_seostaticpage_seostaticpagetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seostaticpage',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='страница'),
        ),
    ]
