# Generated by Django 5.0.3 on 2024-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_alter_seostaticpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seostaticpage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='позиция'),
            preserve_default=False,
        ),
    ]
