# Generated by Django 5.0.3 on 2024-09-22 11:01

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


def connect_to_category(apps, schema_editor):
    SubCategory = apps.get_model('products', 'SubCategory')
    SubCategoryTranslation = apps.get_model('products', 'SubCategoryTranslation')
    SEOCategoryPage = apps.get_model('seo', 'SEOCategoryPage')
    SEOCategoryPageTranslation = apps.get_model('seo', 'SEOCategoryPageTranslation')
    
    for cat in SubCategory.objects.all():
        seo_category_page = SEOCategoryPage.objects.create(
            category=cat
        )
        translations = SubCategoryTranslation.objects.filter(master_id=cat.id)
        for translation in translations:
            lang = translation.language_code
            SEOCategoryPageTranslation.objects.create(
                master_id=seo_category_page.pk,
                language_code=lang,
                header=translation.name,
                title=translation.name,
                description=translation.name
            )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_set_slug_as_translatable_subcategory'),
        ('seo', '0005_seostaticpage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOCategoryPage',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.subcategory')),
            ],
            options={
                'verbose_name': 'SEO для категорий',
                'verbose_name_plural': 'SEO для категорий',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='seostaticpage',
            options={'ordering': ('order',), 'verbose_name': 'SEO для статических страниц', 'verbose_name_plural': 'SEO для статических страниц'},
        ),
        migrations.AlterField(
            model_name='seostaticpage',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='позиция (сортировка списка в админке)'),
        ),
        migrations.CreateModel(
            name='SEOCategoryPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('header', models.CharField(max_length=255, unique=True, verbose_name='h1')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('noindex_follow', models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='seo.seocategorypage')),
            ],
            options={
                'verbose_name': 'SEO для категорий Translation',
                'db_table': 'seo_seocategorypage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(connect_to_category),
    ]
