# Generated by Django 5.0.3 on 2024-09-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_set_slug_as_translatable_subcategory'),
        ('seo', '0006_seocategorypage_alter_seostaticpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seocategorypagetranslation',
            name='header',
        ),
        migrations.AlterField(
            model_name='seocategorypage',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seo', serialize=False, to='products.subcategory', verbose_name='категория'),
        ),
    ]
