# Generated by Django 5.0.3 on 2024-09-22 15:00

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


def connect_to_product(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductTranslation = apps.get_model('products', 'ProductTranslation')
    SEOProductPage = apps.get_model('seo', 'SEOProductPage')
    SEOProductPageTranslation = apps.get_model('seo', 'SEOProductPageTranslation')
    
    for product in Product.objects.all():
        seo_product_page = SEOProductPage.objects.create(
            product=product
        )
        translations = ProductTranslation.objects.filter(master_id=product.id)
        for translation in translations:
            lang = translation.language_code
            SEOProductPageTranslation.objects.create(
                master_id=seo_product_page.pk,
                language_code=lang,
                title=translation.name,
                description=translation.name
            )

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_set_slug_as_translatable_subcategory'),
        ('seo', '0007_remove_seocategorypagetranslation_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOProductPage',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seo', serialize=False, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'SEO для товара',
                'verbose_name_plural': 'SEO для товара',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SEOProductPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('noindex_follow', models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='seo.seoproductpage')),
            ],
            options={
                'verbose_name': 'SEO для товара Translation',
                'db_table': 'seo_seoproductpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(connect_to_product),
    ]
