# Generated by Django 5.0.3 on 2024-09-22 15:43

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posttranslation_content_and_more'),
        ('seo', '0008_seoproductpage_seoproductpagetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPostPage',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seo', serialize=False, to='blog.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'SEO для поста',
                'verbose_name_plural': 'SEO для поста',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SEOPostPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('noindex_follow', models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='seo.seopostpage')),
            ],
            options={
                'verbose_name': 'SEO для поста Translation',
                'db_table': 'seo_seopostpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
