# Generated by Django 5.0.3 on 2024-09-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0010_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocategorypage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='seo.sitemap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seopostpage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='seo.sitemap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoproductpage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='seo.sitemap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seostaticpage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='statics', to='seo.sitemap'),
            preserve_default=False,
        ),
    ]
