# Generated by Django 5.0.3 on 2024-09-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0011_seocategorypage_sitemap_seopostpage_sitemap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seocategorypage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='seo.sitemap'),
        ),
        migrations.AlterField(
            model_name='seopostpage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='seo.sitemap'),
        ),
        migrations.AlterField(
            model_name='seoproductpage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='seo.sitemap'),
        ),
    ]
