# Generated by Django 5.0.3 on 2024-09-26 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0012_alter_seocategorypage_sitemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocategorypagetranslation',
            name='change_freq',
            field=models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='yearly', max_length=7, verbose_name='changefreq'),
        ),
        migrations.AddField(
            model_name='seocategorypagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='seopostpagetranslation',
            name='change_freq',
            field=models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='yearly', max_length=7, verbose_name='changefreq'),
        ),
        migrations.AddField(
            model_name='seopostpagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='seoproductpagetranslation',
            name='change_freq',
            field=models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='yearly', max_length=7, verbose_name='changefreq'),
        ),
        migrations.AddField(
            model_name='seoproductpagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='seostaticpagetranslation',
            name='change_freq',
            field=models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='yearly', max_length=7, verbose_name='changefreq'),
        ),
        migrations.AddField(
            model_name='seostaticpagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='priority'),
        ),
    ]
