# Generated by Django 5.0.3 on 2024-09-26 12:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0013_seocategorypagetranslation_change_freq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seocategorypagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='seopostpagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='seoproductpagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='seostaticpage',
            name='sitemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='statics', to='seo.sitemap'),
        ),
        migrations.AlterField(
            model_name='seostaticpagetranslation',
            name='priority',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='priority'),
        ),
    ]
