# Generated by Django 5.0.3 on 2024-09-30 08:35

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0014_alter_seocategorypagetranslation_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaGenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ctg', 'Категория'), ('prd', 'Товар')], max_length=3, verbose_name='тип')),
                ('instruction', models.TextField(verbose_name='инструкция')),
            ],
            options={
                'verbose_name': 'правило генерации метатегов',
                'verbose_name_plural': 'правила генерации метатегов',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MetaGenerationRuleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='правило генерации Title')),
                ('description', models.CharField(max_length=255, verbose_name='правило генерации Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='seo.metagenerationrule')),
            ],
            options={
                'verbose_name': 'правило генерации метатегов Translation',
                'db_table': 'seo_metagenerationrule_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
