# Generated by Django 5.0.3 on 2024-10-04 08:52

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_tag_product_tags_tagredirectfrom_tagtranslation'),
        ('seo', '0017_alter_cssfile_content_alter_jsfile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metagenerationrule',
            name='type',
            field=models.CharField(choices=[('ctg', 'Категория'), ('prd', 'Товар'), ('tag', 'Тег')], max_length=3, verbose_name='тип'),
        ),
        migrations.CreateModel(
            name='SEOTagPage',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seo', serialize=False, to='products.tag', verbose_name='тег')),
                ('sitemap', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='seo.sitemap')),
            ],
            options={
                'verbose_name': 'SEO для тегов',
                'verbose_name_plural': 'SEO для тегов',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SEOTagPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('noindex_follow', models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">')),
                ('change_freq', models.CharField(choices=[('always', 'always'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('never', 'never')], default='yearly', max_length=7, verbose_name='changefreq')),
                ('priority', models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='priority')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='seo.seotagpage')),
            ],
            options={
                'verbose_name': 'SEO для тегов Translation',
                'db_table': 'seo_seotagpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
