# Generated by Django 5.0.3 on 2024-04-22 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_producttranslation_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='контактное лицо')),
                ('number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='вид деятельности')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='наименование предприятия или И.П.')),
            ],
            options={
                'verbose_name': 'запрос консультации',
                'verbose_name_plural': 'запросы консультаций',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='контактное лицо')),
                ('number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес электронной почты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='адрес доставки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличный расчет'), ('non-cash', 'Безналичный расчет')], max_length=8)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='PriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='контактное лицо')),
                ('number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес электронной почты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'запрос цены',
                'verbose_name_plural': 'запросы цен',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество заказанного товара')),
                ('order_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена единицы товара на момент заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='requests.order', verbose_name='данные заказа')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'заказанный товар',
                'verbose_name_plural': 'заказвнныеы товары',
            },
        ),
    ]
