# Generated by Django 5.0.3 on 2024-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличный расчет'), ('non-cash', 'Безналичный расчет')], default='cash', max_length=8),
            preserve_default=False,
        ),
    ]
