# Generated by Django 5.0.3 on 2024-04-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='контактное лицо')),
                ('number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес электронной почты')),
                ('entity', models.TextField(verbose_name='юр. лицо')),
                ('card', models.CharField(max_length=200, verbose_name='карта партнера')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'запрос на образцы продукции',
                'verbose_name_plural': 'запросы на образцы продукции',
            },
        ),
    ]
