# Generated by Django 5.0.3 on 2024-04-16 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_description'),
        ('requests', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество заказанного товара')),
                ('order_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена единицы товара на момент заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='requests.order', verbose_name='данные заказа')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'заказанный товар',
                'verbose_name_plural': 'заказвнныеы товары',
            },
        ),
    ]
