# Generated by Django 5.0.3 on 2024-04-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerequest',
            name='entity',
            field=models.CharField(max_length=200, verbose_name='юр. лицо'),
        ),
    ]
