# Generated by Django 5.0.3 on 2024-04-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_samplerequest_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('consultationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests.consultationrequest')),
            ],
            options={
                'verbose_name': 'запрос коммерческого предложения',
                'verbose_name_plural': 'запросы коммерческих предложений',
            },
            bases=('requests.consultationrequest',),
        ),
    ]
