# Generated by Django 5.0.3 on 2024-04-04 13:47

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=60, verbose_name='условие для бонуса')),
                ('bonus1', models.CharField(blank=True, max_length=50, null=True, verbose_name='бонус')),
            ],
            options={
                'verbose_name': 'дополнительный бонус к акциям',
                'verbose_name_plural': 'дополнительные бонусы к акциям',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='заголовок акции')),
                ('additional_text', models.CharField(max_length=100, verbose_name='текст под заголовком')),
                ('last_day', models.DateField(verbose_name='последний день акции')),
                ('img', models.ImageField(storage=common.utils.CustomStorage, upload_to='', verbose_name='картинка акции')),
                ('is_active', models.BooleanField(default=True, verbose_name='акция активна')),
                ('bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.bonus')),
            ],
            options={
                'verbose_name': 'Акция на товар',
                'verbose_name_plural': 'Акции на товар',
            },
        ),
    ]
