# Generated by Django 5.0.3 on 2024-04-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='bonus2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='бонус'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='бонус'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus1',
            field=models.CharField(max_length=50, verbose_name='бонус'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.bonus', verbose_name='дополнительные бонусы'),
        ),
    ]
