# Generated by Django 5.0.3 on 2024-04-04 10:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='наименование')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='url')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='текст статьи')),
                ('is_open', models.BooleanField(default=True, verbose_name='вакансия открыта')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
            },
        ),
    ]
