# Generated by Django 5.0.3 on 2024-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
