# Generated by Django 5.0.3 on 2024-04-24 23:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='текст вакансии'),
        ),
    ]
