# Generated by Django 5.0.3 on 2024-04-04 12:21

import common.utils
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название проекта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('preview_image', models.ImageField(storage=common.utils.CustomStorage, upload_to='', verbose_name='изображение, превью')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='текст статьи')),
                ('content_concise', models.TextField(max_length=120, verbose_name='краткое описание проекта')),
                ('customer_log', models.ImageField(storage=common.utils.CustomStorage, upload_to='', verbose_name='логотип заказчика')),
                ('location', models.CharField(max_length=50, verbose_name='место проекта')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
