# Generated by Django 5.0.3 on 2024-04-01 13:08

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название категории')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Charachteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название характеристики')),
            ],
            options={
                'verbose_name': 'характеристика товара',
                'verbose_name_plural': 'характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='CharValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True, verbose_name='значение характеристики')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.charachteristic', verbose_name='название характеристики товара')),
            ],
            options={
                'verbose_name': 'значение характеристики товара',
                'verbose_name_plural': 'значения характеристик товара',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название товара')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='артикул')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='url')),
                ('actual_price', models.PositiveIntegerField(verbose_name='цена')),
                ('current_price', models.PositiveIntegerField(verbose_name='текущая цена (со скидкой)')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('charachteristics', models.ManyToManyField(to='products.charachteristic', verbose_name='характеристики товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=common.utils.upload_product_img_to, verbose_name='изображение товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_urls', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название подкатегории')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(related_name='products', to='products.subcategory', verbose_name='подкатегория товара'),
        ),
    ]
