# Generated by Django 5.0.3 on 2024-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='charachteristics',
            field=models.ManyToManyField(to='products.charvalue', verbose_name='характеристики товара'),
        ),
    ]
