# Generated by Django 5.0.3 on 2024-04-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producttranslation_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(default=32000, verbose_name='позиция в фильтре каталога'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='priority',
            field=models.PositiveSmallIntegerField(default=32000, verbose_name='позиция в фильтре каталога'),
        ),
    ]
