# Generated by Django 5.0.3 on 2024-09-16 13:29

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_priority_subcategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(null=True, upload_to=common.utils.upload_category_img_to, verbose_name='картинка категории'),
        ),
    ]
