# Generated by Django 5.0.3 on 2024-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimg_options_product_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='текущая цена (со скидкой)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название товара'),
        ),
    ]
