# Generated by Django 5.0.3 on 2024-09-17 07:14

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subcategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to=common.utils.upload_group_img_to, verbose_name='картинка группы'),
        ),
    ]
