# Generated by Django 5.0.3 on 2024-04-11 21:26

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_charvalue_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('doc_url', models.FileField(upload_to=common.utils.upload_product_file_to, verbose_name='документ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_urls', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'документ товара',
                'verbose_name_plural': 'документы товара',
            },
        ),
    ]
