# Generated by Django 5.0.3 on 2024-09-19 08:08

from django.db import migrations, models
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
# from django.utils import translation


def set_slug(apps, schema_editor):
    SubCategory = apps.get_model('products', 'SubCategory')
    SubCategoryTranslation = apps.get_model('products', 'SubCategoryTranslation')
    # for lang in settings.LANGUAGES:
        # translation.activate(lang[0])
    for cat in SubCategory.objects.all():
        translations = SubCategoryTranslation.objects.filter(master_id=cat.id)
        for translation in translations:
            lang = translation.language_code
            translation.slug = cat.slug_old if lang == 'ru' else cat.slug_old + lang
            translation.save()
        # for lang in settings.LANGUAGES:
        #   try:
        #       translation = translations.get(language_code=lang[0])
        #       translation.slug = cat.slug_old if lang[0] == 'ru' else cat.slug_old + lang[0]
        #       translation.save()
        #   except ObjectDoesNotExist:
        #       continue


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='slug_old',
        ),
        migrations.AddField(
            model_name='subcategorytranslation',
            name='slug',
            field=models.SlugField(max_length=60, null=True, unique=True, verbose_name='url'),
        ),
        migrations.RunPython(set_slug),
        migrations.AlterField(
            model_name='subcategorytranslation',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='url'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug_old',
        ),
    ]
