# Generated by Django 5.0.3 on 2024-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_set_slug_as_translatable_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='subcategorytranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='url'),
        ),
    ]
