# Generated by Django 5.0.3 on 2024-04-21 12:28

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charvalue',
            options={'verbose_name': 'характеристика товара', 'verbose_name_plural': 'характеристики товаров'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='_slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='_name',
        ),
        migrations.AlterUniqueTogether(
            name='charvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='charachteristics',
        ),
        migrations.AddField(
            model_name='charvalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charachteristics', to='products.product', verbose_name='товар'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название категории')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.category')),
            ],
            options={
                'verbose_name': 'категория Translation',
                'db_table': 'products_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CharValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('key', models.CharField(max_length=50, verbose_name='характеристика')),
                ('value', models.CharField(max_length=50, verbose_name='значение характеристики')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.charvalue')),
            ],
            options={
                'verbose_name': 'характеристика товара Translation',
                'db_table': 'products_charvalue_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название товара')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='url')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='описание товара')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='позиция в выдаче')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name': 'товар Translation',
                'db_table': 'products_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название подкатегории')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'подкатегория Translation',
                'db_table': 'products_subcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='ProductDoc',
        ),
        migrations.RemoveField(
            model_name='charvalue',
            name='char',
        ),
        migrations.RemoveField(
            model_name='charvalue',
            name='value',
        ),
        migrations.DeleteModel(
            name='Charachteristic',
        ),
    ]
