# Generated by Django 5.0.3 on 2024-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategorytranslation',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
