# Generated by Django 5.0.3 on 2024-04-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_name_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charachteristic',
            options={'verbose_name': 'название характеристики товара', 'verbose_name_plural': 'названия характеристик товаров'},
        ),
        migrations.AlterModelOptions(
            name='charvalue',
            options={'verbose_name': 'характеристика товара', 'verbose_name_plural': 'характеристики товаров'},
        ),
        migrations.AlterUniqueTogether(
            name='charvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='charachteristics',
        ),
        migrations.AddField(
            model_name='charvalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charachteristics', to='products.product', verbose_name='товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='позиция в выдаче'),
        ),
    ]
