# Generated by Django 5.0.3 on 2024-04-20 12:35

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_charachteristic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charachteristic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charvalue',
            name='value',
        ),
        migrations.CreateModel(
            name='CharachteristicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название характеристики')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.charachteristic')),
            ],
            options={
                'verbose_name': 'название характеристики товара Translation',
                'db_table': 'products_charachteristic_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='CharValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.CharField(max_length=50, verbose_name='значение характеристики')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.charvalue')),
            ],
            options={
                'verbose_name': 'характеристика товара Translation',
                'db_table': 'products_charvalue_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
