# Generated by Django 5.0.3 on 2024-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_charachteristic_name_remove_charvalue_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charvalue',
            name='char',
        ),
        migrations.AddField(
            model_name='charvaluetranslation',
            name='key',
            field=models.CharField(default=1, max_length=50, verbose_name='характеристика'),
            preserve_default=False,
        ),
    ]
