# Generated by Django 5.0.3 on 2024-10-04 08:52

import apps.products.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_subcategorytranslation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='products.tag', verbose_name='теги'),
        ),
        migrations.CreateModel(
            name='TagRedirectFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.CharField(max_length=60, unique=True, verbose_name='старый url')),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('tr', 'Турецкий'), ('zh', 'Китайский')], default='ru', max_length=2, verbose_name='языковая версия тега старого url')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tag')),
            ],
            options={
                'verbose_name': 'Старый слаг (редирект (seo))',
                'verbose_name_plural': 'Старые слаги (редирект (seo))',
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название тега')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, validators=[apps.products.models.validate_is_tag_slug_old], verbose_name='url')),
                ('last_modified', models.DateField(auto_now=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.tag')),
            ],
            options={
                'verbose_name': 'тег Translation',
                'db_table': 'products_tag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
