# Generated by Django 5.0.3 on 2024-10-05 14:20

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_tag_product_tags_tagredirectfrom_tagtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'фильтр',
                'verbose_name_plural': 'фильтры',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(related_name='products', to='products.filter', verbose_name='фильтры'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='filters',
            field=models.ManyToManyField(related_name='categories', to='products.filter', verbose_name='фильтры'),
        ),
        migrations.CreateModel(
            name='FilterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название фильтра')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.filter')),
            ],
            options={
                'verbose_name': 'фильтр Translation',
                'db_table': 'products_filter_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
