# Generated by Django 5.0.3 on 2024-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_filter_product_filters_subcategory_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
