# Generated by Django 5.0.3 on 2024-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.filter', verbose_name='фильтры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.tag', verbose_name='теги'),
        ),
    ]
