# Generated by Django 5.0.3 on 2024-10-12 11:11

import apps.products.models
import django.db.models.deletion
import parler.fields
import parler.models
import smart_selects.db_fields
from django.db import migrations, models
from django.utils.text import slugify
from unidecode import unidecode


def generate_unique_slug_translated(klass, field):
    origin_slug = slugify(unidecode(field))
    unique_slug = origin_slug
    numb = 1
    while klass.objects.filter(slug=unique_slug).exists():
        unique_slug = f"{origin_slug}-{numb}"
        numb += 1
    return unique_slug


def reassgin_characteristics_to_new_models(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductTranslation = apps.get_model("products", "ProductTranslation")
    Characteristic = apps.get_model("products", "Characteristic")
    CharacteristicTranslation = apps.get_model("products", "CharacteristicTranslation")
    CharacteristicValue = apps.get_model("products", "CharacteristicValue")
    CharacteristicValueTranslation = apps.get_model(
        "products", "CharacteristicValueTranslation"
    )
    ProductCharacteristic = apps.get_model("products", "ProductCharacteristic")

    OldCharachteristic = apps.get_model("products", "CharValue")
    OldCharachteristicTranslation = apps.get_model("products", "CharValueTranslation")

    ru = "ru"
    for oldChar in OldCharachteristic.objects.filter(translations__language_code=ru):
        oldChar.set_current_language(ru)
        newChar = Characteristic.objects.filter(translations__name=oldChar.key).first()
        if newChar is None:
            newChar = Characteristic.objects.create()
            CharacteristicTranslation.objects.create(
                master_id=newChar.pk,
                language_code=ru,
                name=oldChar.key,
                slug=generate_unique_slug_translated(
                    CharacteristicTranslation, oldChar.key
                ),
            )

        newVal = CharacteristicValue.objects.filter(
            translations__name=oldChar.value, characteristic=newChar
        ).first()
        if newVal is None:
            newVal = CharacteristicValue.objects.create(characteristic=newChar)
            CharacteristicValueTranslation.objects.create(
                master_id=newVal.pk,
                language_code=ru,
                name=oldChar.value,
                slug=generate_unique_slug_translated(
                    CharacteristicValueTranslation, oldChar.value
                ),
            )

        ProductCharacteristic.objects.create(
            product=oldChar.product, characteristic=newChar, characteristic_value=newVal
        )


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_product_filters_alter_product_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика товаров",
                "verbose_name_plural": "характеристики товаров",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CharacteristicValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.characteristic",
                        verbose_name="характеристика товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "значение характеристики товаров",
                "verbose_name_plural": "значения характеристик товаров",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.characteristic",
                    ),
                ),
                (
                    "characteristic_value",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="characteristic",
                        chained_model_field="characteristic",
                        on_delete=django.db.models.deletion.CASCADE,
                        sort=False,
                        to="products.characteristicvalue",
                        validators=[
                            apps.products.models.validate_is_value_belong_to_characteristic
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="characteristics",
            field=models.ManyToManyField(
                through="products.ProductCharacteristic", to="products.characteristic"
            ),
        ),
        migrations.CreateModel(
            name="CharacteristicTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="характеристика товара"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=70, unique=True, verbose_name="слаг"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.characteristic",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика товаров Translation",
                "db_table": "products_characteristic_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CharacteristicValueTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=60, verbose_name="значение характеристики товара"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=70, verbose_name="слаг"),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.characteristicvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "значение характеристики товаров Translation",
                "db_table": "products_characteristicvalue_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="productcharacteristic",
            constraint=models.UniqueConstraint(
                fields=("product", "characteristic"),
                name="unique_product_characteristic",
            ),
        ),
        migrations.RunPython(reassgin_characteristics_to_new_models, None),
    ]
