# Generated by Django 5.0.3 on 2024-10-13 15:48

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_characteristic_characteristicvalue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcharacteristic",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product", verbose_name="товар"
            ),
        ),
        migrations.AlterField(
            model_name="productcharacteristic",
            name="characteristic_value",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="characteristic",
                chained_model_field="characteristic",
                on_delete=django.db.models.deletion.CASCADE,
                sort=False,
                to="products.characteristicvalue",
                verbose_name="значение",
            ),
        ),
        migrations.AlterModelOptions(
            name="productcharacteristic",
            options={"verbose_name": "характеристики товара", "verbose_name_plural": "характеристики товара"},
        ),
        migrations.AlterField(
            model_name="characteristicvaluetranslation",
            name="name",
            field=models.CharField(blank=True, max_length=60, verbose_name="значение характеристики товара"),
        ),
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.ManyToManyField(
                through="products.ProductCharacteristic", to="products.characteristic", verbose_name="характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="productcharacteristic",
            name="characteristic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.characteristic",
                verbose_name="характеристика",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="charvaluetranslation",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="filtertranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="filtertranslation",
            name="master",
        ),
        migrations.RemoveField(
            model_name="charvaluetranslation",
            name="master",
        ),
        migrations.RemoveField(
            model_name="product",
            name="filters",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="filters",
        ),
        migrations.DeleteModel(
            name="CharValueTranslation",
        ),
        migrations.DeleteModel(
            name="CharValue",
        ),
        migrations.DeleteModel(
            name="FilterTranslation",
        ),
        migrations.DeleteModel(
            name="Filter",
        ),
    ]
