# Generated by Django 5.0.3 on 2024-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_charvaluetranslation_master_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimg',
            options={'ordering': ('product', 'order'), 'verbose_name': 'изображение товара', 'verbose_name_plural': 'изображения товара'},
        ),
        migrations.AddField(
            model_name='productimg',
            name='order',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='порядок'),
        ),
    ]
