# Generated by Django 5.0.3 on 2024-10-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productimg_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcharacteristic',
            name='unique_product_characteristic',
        ),
        migrations.AddConstraint(
            model_name='productcharacteristic',
            constraint=models.UniqueConstraint(fields=('product', 'characteristic', 'characteristic_value'), name='unique_product_characteristic_value'),
        ),
    ]
