# Generated by Django 5.0.3 on 2024-09-22 15:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_content_remove_post_content_concise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='текст статьи'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='url'),
        ),
    ]
