# Generated by Django 5.0.3 on 2024-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posttranslation_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='url'),
        ),
    ]
