# Generated by Django 5.0.3 on 2024-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posttranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
