# Generated by Django 5.0.3 on 2024-09-30 07:04

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postredirectfrom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postredirectfrom',
            options={'verbose_name': 'Старый слаг (редирект (seo))', 'verbose_name_plural': 'Старые слаги (редиректы (seo))'},
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, validators=[apps.blog.models.validate_is_slug_old], verbose_name='url'),
        ),
    ]
