# Generated by Django 5.0.3 on 2024-04-04 09:07

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='категория вопроса')),
            ],
            options={
                'verbose_name': 'категория вопроса',
                'verbose_name_plural': 'категории вопроса',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='вопрос')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='ответ')),
                ('categories', models.ManyToManyField(related_name='faqs', to='faq.faqcategory', verbose_name='категории вопроса')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
